spring.application.name=gateway-service

server.port=8080

#Api services URI
product.service.url=http://localhost:8082
inventory.service.url=http://localhost:8089
order.service.url=http://localhost:8087
